<template>
<div class="prose" data-chapter="1" data-section="rules">
<p>Теперь выберите <strong>наследие</strong> вашего персонажа. Этот аспект включает два элемента — его происхождение и принадлежность к сообществу.</p>
<h4 id="выберите-происхождение"><span class="marker" data-marker="chapter"></span>Выберите происхождение<a class="anchor" href="#выберите-происхождение" aria-label="Ссылка на раздел"></a></h4>
<p>Происхождение персонажа отражает его родословную, влияет на физические характеристики и даёт два уникальных свойства. Возьмите карточку одного из представленных ниже происхождений и впишите её название в поле «Наследие» на листе персонажа.</p>
<div class="table-wrap"><table class="dataviewjs-block" data-tag="ancestry"><tbody><tr><td><a href="/rules/preparing-for-adventure/ancestry/giant">Великан</a></td><td><a href="/rules/preparing-for-adventure/ancestry/galapa">Галапа</a></td><td><a href="/rules/preparing-for-adventure/ancestry/goblin">Гоблин</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/dwarf">Дварф</a></td><td><a href="/rules/preparing-for-adventure/ancestry/drakona">Драконид</a></td><td><a href="/rules/preparing-for-adventure/ancestry/infernis">Инфернис</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/katari">Катари</a></td><td><a href="/rules/preparing-for-adventure/ancestry/ribbet">Кваква</a></td><td><a href="/rules/preparing-for-adventure/ancestry/clank">Кланк</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/orc">Орк</a></td><td><a href="/rules/preparing-for-adventure/ancestry/halfling">Полурослик</a></td><td><a href="/rules/preparing-for-adventure/ancestry/simiah">Симиан</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/mixed-ancestry">Смешанное</a></td><td><a href="/rules/preparing-for-adventure/ancestry/faun">Фавн</a></td><td><a href="/rules/preparing-for-adventure/ancestry/faerie">Фейри</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/firbolg">Филборг</a></td><td><a href="/rules/preparing-for-adventure/ancestry/fungril">Фунгрил</a></td><td><a href="/rules/preparing-for-adventure/ancestry/human">Человек</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/ancestry/elf">Эльф</a></td><td></td><td></td></tr></tbody></table></div>
<h4 id="выберите-сообщество"><span class="marker" data-marker="chapter"></span>Выберите сообщество<a class="anchor" href="#выберите-сообщество" aria-label="Ссылка на раздел"></a></h4>
<p>Затем выберите сообщество из доступных карточек сообществ. На сообщество вашего персонажа влияют его географическое положение, ценности и цели. Оно определяет культуру, в которой вырос персонаж, и может отражаться на его внешнем виде, поведении и подходе к различным ситуациям. Каждое сообщество даёт особое свойство, которое вы можете использовать в игре. Возьмите карточку одного из представленных ниже сообществ и впишите его название в поле «Наследие» на листе персонажа.</p>
<div class="table-wrap"><table class="dataviewjs-block" data-tag="community"><tbody><tr><td><a href="/rules/preparing-for-adventure/community/highborne">Высшее</a></td><td><a href="/rules/preparing-for-adventure/community/ridgeborne">Горное</a></td><td><a href="/rules/preparing-for-adventure/community/orderborne">Догматичное</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/community/wanderborne">Кочевое</a></td><td><a href="/rules/preparing-for-adventure/community/slyborne">Криминальное</a></td><td><a href="/rules/preparing-for-adventure/community/wildborne">Лесное</a></td></tr><tr><td><a href="/rules/preparing-for-adventure/community/seaborne">Морское</a></td><td><a href="/rules/preparing-for-adventure/community/loreborne">Научное</a></td><td><a href="/rules/preparing-for-adventure/community/underborne">Подземное</a></td></tr></tbody></table></div>
<h4 id="языки"><span class="marker" data-marker="chapter"></span>Языки<a class="anchor" href="#языки" aria-label="Ссылка на раздел"></a></h4>
<p>В Daggerheart не нужно выбирать конкретные языки для персонажа: все говорят на общем языке (обычным способом или магическим — на ваше усмотрение), а язык жестов понятен во всех культурах и сообществах. Особые региональные языки — только по согласованию с группой.</p>
<hr>
</div>
</template>
