<template>
<div class="prose" data-chapter="1" data-section="rules">
<p>Первый шаг в создании персонажа — это выбор <strong>класса</strong>, за который вы хотите играть. Каждый класс — это ролевой архетип, который определяет, какие способности будут доступны вам на протяжении всей кампании. Например, вы можете выбрать стража, если хотите быть «танком» в своей группе — тем, кто бросается в бой сломя голову и защищает других ценой своей жизни. Или, может быть, вы захотите сыграть за волшебника, который использует уникальные заклинания для решения проблем, лечит союзников и применяет изощрённую боевую магию.</p>
<p>После выбора класса вы также выберете <strong>подкласс</strong>. Подклассы — это подгруппы каждого класса, которые помогают точнее определить архетип вашего персонажа.</p>
<h4 id="бард"><span class="marker" data-marker="chapter"></span>Бард<a class="anchor" href="#бард" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/bard/troubadour" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classBardTroubadour.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Трубадур</p><p class="subclass-card-desc">Выбирайте Трубадура, если хотите поддерживать союзников музыкой.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/bard/wordsmith" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classBardWordsmith.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Мастер слова</p><p class="subclass-card-desc">Выбирайте Мастера слова, если вы хотите использовать умную игру слов и захватывать внимание публики.</p></a></div>
<h4 id="друид"><span class="marker" data-marker="chapter"></span>Друид<a class="anchor" href="#друид" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/druid/warden-of-the-elements" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classDruidWardenOfTheElements.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Хранитель стихий</p><p class="subclass-card-desc">Выбирайте Хранителя стихий, если хотите воплотить необузданные силы природы.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/druid/warden-of-renewal" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classDruidWardenOfRenewal.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Хранитель жизни</p><p class="subclass-card-desc">Выбирайте Хранителя жизни, если хотите использовать мощную магию для лечения своих союзников.</p></a></div>
<h4 id="страж"><span class="marker" data-marker="chapter"></span>Страж<a class="anchor" href="#страж" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/guardian/stalwart" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classGuardianStalwart.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Непоколебимый</p><p class="subclass-card-desc">Выбирайте Непоколебимого, если хотите выдерживать мощные удары и продолжать сражаться.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/guardian/vengeance" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classGuardianVengeance.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Мститель</p><p class="subclass-card-desc">Выбирайте Мстителя, если хотите беспощадно карать врагов, причинивших вред вам или вашим союзникам.</p></a></div>
<h4 id="следопыт"><span class="marker" data-marker="chapter"></span>Следопыт<a class="anchor" href="#следопыт" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/ranger/beastbound" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classRangerBeastbound.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Звериные узы</p><p class="subclass-card-desc">Выбирайте Звериные узы, если хотите создать неразрывную связь с животным-союзником.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/ranger/wayfinder" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classRangerWayfinder.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Охотник</p><p class="subclass-card-desc">Выбирайте Охотника, если хотите выслеживать добычу и наносить смертоносные удары.</p></a></div>
<h4 id="плут"><span class="marker" data-marker="chapter"></span>Плут<a class="anchor" href="#плут" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/rogue/nightwalker" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classRogueNightwalker.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Ночной странник</p><p class="subclass-card-desc">Выбирайте Ночного странника, если хотите управлять тенями и перемещаться через них.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/rogue/syndicate" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classRogueSyndicate.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Синдикат</p><p class="subclass-card-desc">Выбирайте Синдикат, если хотите иметь сеть полезных знакомств в каждом уголке мира.</p></a></div>
<h4 id="серафим"><span class="marker" data-marker="chapter"></span>Серафим<a class="anchor" href="#серафим" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/seraph/winged-sentinel" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classSerpahWingedSentinel.webp" width="1600" height="529" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Крылатый страж</p><p class="subclass-card-desc">Выбирайте Крылатого стража, если хотите парить в небесах и наносить врагам сокрушающие удары с небес.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/seraph/divine-wielder" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classSeraphDivineWielder.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Божественный воитель</p><p class="subclass-card-desc">Выбирайте Божественного воителя, если хотите доминировать на поле боя с помощью легендарного оружия.</p></a></div>
<h4 id="чародей"><span class="marker" data-marker="chapter"></span>Чародей<a class="anchor" href="#чародей" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/sorcerer/elemental-origin" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classSorcererElementalOrigin.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Стихийный исток</p><p class="subclass-card-desc">Выбирайте Стихийный исток, если хотите творчески использовать необузданную магию стихий.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/sorcerer/primal-origin" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classSorcererPrimalOrigin.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Первородный исток</p><p class="subclass-card-desc">Выбирайте Первородный исток, если хотите расширить возможности своих заклинаний мощными эффектами.</p></a></div>
<h4 id="воин"><span class="marker" data-marker="chapter"></span>Воин<a class="anchor" href="#воин" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/warrior/call-of-the-brave" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classWarriorCallOfTheBrave.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Зов Отваги</p><p class="subclass-card-desc">Выбирайте Зов отваги, если хотите обращать мощь врагов в свою силу.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/warrior/call-of-the-slayer" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classWarriorCallOfTheSlayer.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Зов Резни</p><p class="subclass-card-desc">Выбирайте Зов резни, если хотите с невероятной силой сокрушать врагов.</p></a></div>
<h4 id="волшебник"><span class="marker" data-marker="chapter"></span>Волшебник<a class="anchor" href="#волшебник" aria-label="Ссылка на раздел"></a></h4>
<div class="subclass-cards"><a class="subclass-card" href="/rules/preparing-for-adventure/classes/wizard/school-of-knowledge" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classWizardSchoolOfKnowledge.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Школа Знания</p><p class="subclass-card-desc">Выбирайте Школу знания, если стремитесь к глубокому пониманию окружающего мира.</p></a><a class="subclass-card" href="/rules/preparing-for-adventure/classes/wizard/school-of-war" data-has-art="true"><figure class="subclass-card-art"><img src="/rollwithhope/images/Banners/Subclasses/classWizardSchoolOfWar.webp" width="1600" height="533" loading="lazy" alt=""></figure><p class="subclass-card-eyebrow">Подкласс</p><p class="subclass-card-title">Школа Войны</p><p class="subclass-card-desc">Выбирайте Школу войны, если хотите быть обучены использовать магию как оружие.</p></a></div>
<h4 id="лист-персонажа-и-материалы-подкласса"><span class="marker" data-marker="chapter"></span>Лист персонажа и материалы подкласса<a class="anchor" href="#лист-персонажа-и-материалы-подкласса" aria-label="Ссылка на раздел"></a></h4>
<p>Выбрав класс, возьмите соответствующий лист персонажа и краткую памятку по классу, затем определитесь с подклассом и получите его базовую карточку. Лист персонажа — рабочий документ для параметров героя, так что держите под рукой бумажную или цифровую копию. Заполняя бумажный вариант, пишите карандашом: значения будут меняться по мере роста уровня. Образец заполненного листа — в разделе «Пример персонажа». Все листы персонажей и памятки по классам можно скачать на официальном сайте Daggerheart; базовый лист персонажа также встроен в приложение игры.</p>
<h4 id="запишите-свой-уровень"><span class="marker" data-marker="chapter"></span>Запишите свой уровень<a class="anchor" href="#запишите-свой-уровень" aria-label="Ссылка на раздел"></a></h4>
<p>Персонажи в Daggerheart начинают с 1-го уровня. Укажите свой уровень в соответствующем поле в верхней части листа персонажа и не забывайте обновлять его каждый раз, когда ваш персонаж получает новый уровень. Мы рекомендуем начинать кампанию с 1-го уровня, но более опытная группа может начать с более высокого, если так предпочитает мастер и игроки.</p>
<h4 id="укажите-детали-персонажа"><span class="marker" data-marker="chapter"></span>Укажите детали персонажа<a class="anchor" href="#укажите-детали-персонажа" aria-label="Ссылка на раздел"></a></h4>
<p>На любом этапе создания персонажа вы можете вписать его имя и предпочитаемое обращение в верхней строке листа, а также заполнить раздел с описанием персонажа в руководстве. Для некоторых людей имя и внешний вид персонажа являются приоритетными, а другим требуется время, чтобы найти подходящие варианты. Главное — чтобы к моменту завершения создания персонажей у всех за столом были готовы имена и описания; а порядок выполнения этих шагов не имеет значения.</p>
<h4 id="свойства-класса"><span class="marker" data-marker="chapter"></span>Свойства класса<a class="anchor" href="#свойства-класса" aria-label="Ссылка на раздел"></a></h4>
<p>Каждый класс начинается с одним или несколькими уникальными <strong>свойствами класса</strong>. Вам не нужно записывать их вручную — они уже указаны в левом нижнем углу листа персонажа соответствующего класса. Эти свойства доступны только вашему классу. Если одно из них требует сделать выбор во время создания персонажа, примите это решение до начала первой сессии.</p>
<hr>
</div>
</template>
